name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [6.x, 8.x, 9.x, 10.x, 12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
      env:
        CI: true
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test-cov
