name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Install Packages
      run: npm install
      env:
        CI: true
    - name: Lint
      run: npm run lint

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        eslint: [8]
        node: [14, 16, 17, 18, 19, 20, 21]
        include:
          - os: windows-latest
            eslint: 8
            node: 16
          - os: macOS-latest
            eslint: 8
            node: 16
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Install Packages
      run: npm install
      env:
        CI: true
    - name: Install ESLint@${{  matrix.eslint  }}
      run: npm install eslint@${{  matrix.eslint  }}
    - name: Test
      run: npm run test
