name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
    - name: Install Packages
      run: npm install
      env:
        CI: true
    - name: Lint
      run: npm run lint

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ["8.10.0", 8.x, 10.x, 12.x, 13.x, 14.x]
        include:
        - os: windows-latest
          node: "12.x"
        - os: macOS-latest
          node: "12.x"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
      env:
        CI: true
    - name: Test
      run: npm run test-cov
